# .goreleaser.yml

builds:
  - id: "thola"

    ignore:
      - goos: linux
        goarch: 386

    main: ./main.go
    binary: thola

    ldflags:
      - -s -w
    env:
      - CGO_ENABLED=0

  - id: "thola-client"

    ignore:
      - goos: linux
        goarch: 386

    main: ./main.go
    binary: thola-client

    flags:
      - -tags=client
    ldflags:
      - -s -w
    env:
      - CGO_ENABLED=0

archives:
  - builds:
      - thola
      - thola-client
      
    replacements:
      amd64: 64-bit
      darwin: macOS