name: "ECS4110"

config:
  components:
    cpu: true

match:
  logical_operator: "OR"
  conditions:
    - type: SysObjectID
      match_mode: startsWith
      values:
        - .1.3.6.1.4.1.259.10.1.39.

components:
  cpu:
    properties:
      detection: snmpwalk
      values:
        load:
          oid: .1.3.6.1.4.1.259.10.1.39.1.39.2.3