name: "comware"

match:
  logical_operator: "OR"
  conditions:
    - type: SysObjectID
      match_mode: startsWith
      values:
        - ".1.3.6.1.4.1.25506."

identify:
  properties:
    vendor:
      - detection: constant
        value: "HPE"
    model:
      - detection: snmpget
        oid: ".1.3.6.1.2.1.47.1.1.1.1.7.1"
    os_version:
      - detection: SysDescription
        operators:
          - type: modify
            modify_method: regexSubmatch
            regex: 'Software Version ([^,]+),'
            format: "$1"