name: ekinops

match:
  conditions:
    - type: SysObjectID
      match_mode: startsWith
      values:
        - .1.3.6.1.4.1.20044
  logical_operator: OR

identify:
  properties:
    vendor:
      - detection: constant
        value: "Ekinops"
    model:
      - detection: snmpget
        oid: ".1.3.6.1.2.1.1.1.0"
        operators:
          - type: modify
            modify_method: regexSubmatch
            regex: "^Ekinops 360 Platform, ([A-Z0-9]+), Release"
            format: "$1"
    serial_number:
      - detection: snmpget
        oid: ".1.3.6.1.4.1.20044.7.6.8.0"
        operators:
          - type: modify
            modify_method: regexSubmatch
            regex: 'Serial Number\s+:\s+([0-9]+)'
            format: "$1"
    os_version:
      - detection: snmpget
        oid: ".1.3.6.1.2.1.1.1.0"
        operators:
          - type: modify
            modify_method: regexSubmatch
            regex: 'Release\s+([0-9\.]+)'
            format: "$1"