name: oracle-acme

config:
  components:
    cpu: true
    memory: true
    sbc: true
    hardware_health: true

match:
  type: SysObjectID
  match_mode: startsWith
  values:
    - .1.3.6.1.4.1.9148.1

identify:
  properties:
    vendor:
      - detection: constant
        value: "Oracle"
    model:
      - detection: SysObjectID
        operators:
          - type: modify
            modify_method: map
            mappings: sysObjectID.yaml
    model_series:
      - detection: Model
        operators:
          - type: modify
            modify_method: regexReplace
            regex: "[0-9]{3}$"
            replace: "000"

components:
  cpu:
    load:
      - detection: snmpget
        oid: .1.3.6.1.4.1.9148.3.2.1.1.1.0
  memory:
    usage:
      - detection: snmpget
        oid: .1.3.6.1.4.1.9148.3.2.1.1.2.0
  sbc:
    agents:
      detection: snmpwalk
      values:
        hostname:
          oid: 1.3.6.1.4.1.9148.3.2.1.2.1.1.2
        current_active_sessions_inbound:
          oid: 1.3.6.1.4.1.9148.3.2.1.2.1.1.4
        current_session_rate_inbound:
          oid: 1.3.6.1.4.1.9148.3.2.1.2.1.1.5
        current_active_sessions_outbound:
          oid: 1.3.6.1.4.1.9148.3.2.1.2.1.1.6
        current_session_rate_outbound:
          oid: 1.3.6.1.4.1.9148.3.2.1.2.1.1.7
        period_asr:
          oid: 1.3.6.1.4.1.9148.3.2.1.2.1.1.19
        status:
          oid: 1.3.6.1.4.1.9148.3.2.1.2.1.1.22
    realms:
      detection: snmpwalk
      values:
        name:
          oid: 1.3.6.1.4.1.9148.3.2.1.2.4.1.2
        current_active_sessions_inbound:
          oid: 1.3.6.1.4.1.9148.3.2.1.2.4.1.3
        current_session_rate_inbound:
          oid: 1.3.6.1.4.1.9148.3.2.1.2.4.1.4
        current_active_sessions_outbound:
          oid: 1.3.6.1.4.1.9148.3.2.1.2.4.1.5
        current_session_rate_outbound:
          oid: 1.3.6.1.4.1.9148.3.2.1.2.4.1.6
        period_asr:
          oid: 1.3.6.1.4.1.9148.3.2.1.2.4.1.18
        active_local_contacts:
          oid: 1.3.6.1.4.1.9148.3.2.1.2.4.1.31
        status:
          oid: 1.3.6.1.4.1.9148.3.2.1.2.4.1.30
    global_call_per_second:
      - detection: snmpget
        oid: .1.3.6.1.4.1.9148.3.2.1.1.6.0
    global_concurrent_sessions:
      - detection: snmpget
        oid: .1.3.6.1.4.1.9148.3.2.1.1.5.0
    active_local_contacts:
      - detection: snmpget
        oid: .1.3.6.1.4.1.9148.3.2.1.1.11.0
    transcoding_capacity:
      - detection: snmpget
        oid: .1.3.6.1.4.1.9148.3.2.1.1.34.0
    license_capacity:
      - detection: snmpget
        oid: .1.3.6.1.4.1.9148.3.2.1.1.10.0
    system_redundancy:
      - detection: snmpget
        oid:  .1.3.6.1.4.1.9148.3.2.1.1.4.0
    system_health_score:
      - detection: snmpget
        oid: .1.3.6.1.4.1.9148.3.2.1.1.3.0
  hardware_health:
    environment_monitor_state:
      - detection: snmpget
        oid: .1.3.6.1.4.1.9148.3.3.1.1.0
    fans:
      detection: snmpwalk
      values:
        description:
          oid: 1.3.6.1.4.1.9148.3.3.1.4.1.1.3
        state:
          oid: 1.3.6.1.4.1.9148.3.3.1.4.1.1.5
    power_supply:
      detection: snmpwalk
      values:
        description:
          oid: .1.3.6.1.4.1.9148.3.3.1.5.1.1.3
        state:
          oid: .1.3.6.1.4.1.9148.3.3.1.5.1.1.4
