name: oracle-acme

config:
  components:
    cpuComponent: true

match:
  type: SysObjectID
  match_mode: startsWith
  values:
    - .1.3.6.1.4.1.9148.1

identify:
  properties:
    vendor:
      - detection: constant
        value: "Oracle"
    model:
      - detection: SysObjectID
        operators:
          - type: modify
            modify_method: map
            mappings: sysObjectID.yaml
    model_series:
      - detection: Model
        operators:
          - type: modify
            modify_method: regexReplace
            regex: "[0-9]{3}$"
            replace: "000"