name: "rad"

match:
  logical_operator: "OR"
  conditions:
    - type: SysObjectID
      match_mode: startsWith
      values:
        - .1.3.6.1.4.1.164.

identify:
  properties:
    vendor:
      - detection: constant
        value: "RAD"
    model:
      - detection: snmpget
        oid: .1.3.6.1.2.1.47.1.1.1.1.7.1
        operators:
          - type: modify
            modify_method: regexSubmatch
            regex: '^(\S+)'
            format: "$1"
    serial_number:
      - detection: snmpget
        oid: .1.3.6.1.2.1.2.2.1.6.1
        use_raw_result: true
        operators:
          - type: modify
            modify_method: regexSubmatch
            regex: '(.{2})(.{2})(.{2})(.{2})(.{2})(.{2})'
            format: "$1:$2:$3:$4:$5:$6"
            return_on_mismatch: true
    os_version:
      - detection: snmpget
        oid: .1.3.6.1.2.1.47.1.1.1.1.10.1