name: "arista_eos"

match:
  logical_operator: "OR"
  conditions:
    - type: SysDescription
      match_mode: contains
      values:
        - "Arista Networks EOS"

identify:
  properties:
    vendor:
      - detection: constant
        value: "Arista Networks"
    os_version:
      - detection: SysDescription
        oid: "1.3.6.1.2.1.1.1.0"
        operators:
          - type: modify
            modify_method: regexSubmatch
            regex: 'Arista Networks EOS version ([^\s]+)'
            format: "$1"