name: "aviat"

match:
  logical_operator: "OR"
  conditions:
    - type: SysObjectID
      match_mode: startsWith
      values:
        - ".1.3.6.1.4.1.2509.11.1.1."

identify:
  properties:
    vendor:
      - detection: constant
        value: "AVIAT Networks"
    model:
      - detection: snmpget
        oid: ".1.3.6.1.2.1.47.1.1.1.1.13.2"
    serial_number:
      - detection: snmpget
        oid: ".1.3.6.1.2.1.47.1.1.1.1.11.2"
    os_version:
      - detection: snmpget
        oid: ".1.3.6.1.2.1.47.1.1.1.1.10.2"