name: ceraos

match:
  conditions:
    - match_mode: startsWith
      type: SysObjectID
      values:
        - .1.3.6.1.4.1.2281.
  logical_operator: OR

config:
  snmp:
    max_oids: 1

identify:
  properties:
    vendor:
      - detection: constant
        value: "Ceragon"
    model:
      - detection: SysObjectID
        operators:
          - type: modify
            modify_method: map
            mappings: sysObjectID.yaml
          - type: filter
            filter_method: startsWith
            value: "IP-20"
            return_on_mismatch: true
          - type: switch
            switch_value: snmpwalkCount
            oid: 1.3.6.1.2.1.2.2.1.2
            snmp_result_filter:
              filter_method: equals
              value: "Radio"
            cases:
              - case: 2
                operators:
                  - type: modify
                    modify_method: addSuffix
                    value: " 2 radio"
    model_series:
      - detection: Model
        operators:
          - type: modify
            modify_method: regexSubmatch
            regex: '^(IP-[0-9]+)'
            format: "$1"
    serial_number:
      - detection: snmpget
        oid: ".1.3.6.1.4.1.2281.10.1.2.10.1.1.6.127"
    os_version:
      - detection: snmpget
        oid: ".1.3.6.1.4.1.2281.10.4.1.13.1.1.4.1"

components:
  interfaces:
    properties:
      detection: snmpwalk
      values:
        radio:
          values:
            level_in:
              oid: 1.3.6.1.4.1.2281.10.5.1.1.2
            level_out:
              oid: 1.3.6.1.4.1.2281.10.5.1.1.3
            maxbitrate_out:
              oid: 1.3.6.1.4.1.2281.10.7.4.1.1.7
              operators:
                - type: modify
                  modify_method: multiply
                  value:
                    detection: constant
                    value: 1000
            maxbitrate_in:
              oid: 1.3.6.1.4.1.2281.10.7.4.1.1.11
              operators:
                - type: modify
                  modify_method: multiply
                  value:
                    detection: constant
                    value: 1000
  cpu:
    properties:
      detection: snmpwalk
      values:
        load:
          oid: .1.3.6.1.4.1.2021.10.1.3.2
          operators:
            - type: modify
              modify_method: multiply
              value:
                detection: constant
                value: 100