name: ekinops

match:
  conditions:
    - type: SysObjectID
      match_mode: startsWith
      values:
        - .1.3.6.1.4.1.20044
  logical_operator: OR

identify:
  properties:
    vendor:
      - detection: constant
        value: "Ekinops"
    model:
      - detection: snmpget
        oid: ".1.3.6.1.2.1.1.1.0"
        operators:
          - type: modify
            modify_method: regexSubmatch
            regex: '^Ekinops 360 Platform, ([A-Z0-9]+), Release'
            format: "$1"
    serial_number:
      - detection: snmpget
        oid: ".1.3.6.1.4.1.20044.7.6.8.0"
        operators:
          - type: modify
            modify_method: regexSubmatch
            regex: 'Serial Number\s+:\s+([0-9]+)'
            format: "$1"
    os_version:
      - detection: snmpget
        oid: ".1.3.6.1.2.1.1.1.0"
        operators:
          - type: modify
            modify_method: regexSubmatch
            regex: 'Release\s+([0-9\.]+)'
            format: "$1"

components:
  interfaces:
    properties:
      detection: snmpwalk
      inherit_values: false
      values:
        ifIndex:
          oid: 1.3.6.1.2.1.2.2.1.1
        ifDescr:
          oid: 1.3.6.1.2.1.2.2.1.2
        ifType:
          oid: 1.3.6.1.2.1.2.2.1.3
          operators:
            - type: modify
              modify_method: map
              mappings: ifType.yaml
        ifPhysAddress:
          oid: 1.3.6.1.2.1.2.2.1.6
          use_raw_result: true
          operators:
            - type: modify
              modify_method: regexSubmatch
              regex: '(.{2})(.{2})(.{2})(.{2})(.{2})(.{2})'
              format: "$1:$2:$3:$4:$5:$6"
              return_on_mismatch: true
        ifAdminStatus:
          oid: 1.3.6.1.2.1.2.2.1.7
          operators:
            - type: modify
              modify_method: map
              ignore_on_mismatch: true
              mappings:
                "1": "up"
                "2": "down"
                "3": "testing"
        ifOperStatus:
          oid: 1.3.6.1.2.1.2.2.1.8
          operators:
            - type: modify
              modify_method: map
              ignore_on_mismatch: true
              mappings:
                "1": "up"
                "2": "down"
                "3": "testing"
                "4": "unknown"
                "5": "dormant"
                "6": "notPresent"
                "7": "lowerLayerDown"
        ifName:
          oid: 1.3.6.1.2.1.31.1.1.1.1