name: fortigate

config:
  components:
    cpu: true
    memory: true
    disk: true
    hardware_health: true
    high_availability: true

match:
  conditions:
    - match_mode: startsWith
      type: SysObjectID
      values:
        - .1.3.6.1.4.1.12356.101.1
  logical_operator: OR

identify:
  properties:
    vendor:
      - detection: constant
        value: "Fortinet"
    model:
      - detection: SysObjectID
        operators:
          - type: modify
            modify_method: map
            mappings: sysObjectID.yaml
    serial_number:
      - detection: snmpget
        oid: 1.3.6.1.2.1.47.1.1.1.1.11.1
    os_version:
      - detection: snmpget
        oid: 1.3.6.1.4.1.12356.101.4.1.1.0
        operators:
          - type: modify
            modify_method: regexSubmatch
            regex: '^([^,]+),'
            format: "$1"

components:
  cpu:
    properties:
      detection: snmpwalk
      values:
        load:
          oid: .1.3.6.1.4.1.12356.101.4.1.3
  memory:
    properties:
      detection: snmpwalk
      values:
        usage:
          oid: .1.3.6.1.4.1.12356.101.4.1.4.0
  disk:
    properties:
      detection: snmpwalk
      values:
        available:
          oid: "1.3.6.1.4.1.12356.101.4.1.7"
          operators:
            - type: modify
              modify_method: multiply
              value:
                detection: constant
                value: 1000000
        used:
          oid: "1.3.6.1.4.1.12356.101.4.1.6"
          operators:
            - type: modify
              modify_method: multiply
              value:
                detection: constant
                value: 1000000