name: ironware

config:
  snmp:
    max_repetitions: 1
  components:
    cpu: true
    memory: true
    hardware_health: true

match:
  conditions:
    - match_mode: startsWith
      type: SysObjectID
      values:
        - .1.3.6.1.4.1.1991
  logical_operator: OR

identify:
  properties:
    vendor:
      - detection: constant
        value: "Brocade"
    serial_number:
      - detection: snmpget
        oid: "1.3.6.1.4.1.1991.1.1.1.1.2.0"
    model:
      - detection: SysObjectID
        operators:
          - type: modify
            modify_method: map
            mappings: sysObjectID.yaml
    os_version:
      - detection: snmpget
        oid: "1.3.6.1.4.1.1991.1.1.2.1.49.0"

components:
  memory:
    properties:
      detection: snmpwalk
      values:
        usage:
          oid: .1.3.6.1.4.1.1991.1.1.2.1.53.0
  hardware_health:
    fans:
      detection: snmpwalk
      values:
        description:
          oid: .1.3.6.1.4.1.1991.1.1.1.3.1.1.2
        state:
          oid: .1.3.6.1.4.1.1991.1.1.1.3.1.1.3
          operators:
            - type: modify
              modify_method: map
              mappings:
                1: "unknown"
                2: "normal"
                3: "critical"
    temperature:
      detection: snmpwalk
      values:
        description:
          oid: .1.3.6.1.4.1.1991.1.1.2.13.1.1.3
        temperature:
          oid: .1.3.6.1.4.1.1991.1.1.2.13.1.1.4