name: junos

config:
  snmp:
    max_repetitions: 1
  components:
    cpu: true
    memory: true

match:
  logical_operator: OR
  conditions:
    - match_mode: startsWith
      type: SysObjectID
      values:
        - .1.3.6.1.4.1.2636.
    - match_mode: contains
      type: SysDescription
      values:
        - kernel JUNOS
        - kernel Junos

identify:
  properties:
    vendor:
      - detection: constant
        value: "Juniper"
    serial_number:
      - detection: snmpget
        oid: "1.3.6.1.4.1.2636.3.1.3.0"
    model:
      - detection: SysDescription
        operators:
          - type: modify
            modify_method: regexSubmatch
            regex: '^Juniper Networks, Inc\.\s([^,^\s^$\n]+( \[[^\]]+\])?)(,|\s|$|\n)'
            format: "$1"
          - type: modify
            modify_method: toUpperCase
      - detection: SysObjectID
        operators:
          - type: modify
            modify_method: map
            mappings: sysObjectID.yaml
    os_version:
      - detection: SysDescription
        operators:
          - type: modify
            modify_method: regexSubmatch
            regex: 'JUNOS ([^\s^\n^,]+)'
            format: "$1"

components:
  memory:
    usage:
      - detection: snmpget
        oid: .1.3.6.1.4.1.2636.3.1.13.1.11.9.1.0.0