name: "linux"

config:
  components:
    cpu: true
    memory: true
    disk: true
    server: true

match:
  logical_operator: OR
  conditions:
    - type: SysObjectID
      match_mode: startsWith
      values:
        - ".1.3.6.1.4.1.8072.3.2.10"
    - type: SysDescription
      match_mode: regex
      values:
        - '^Linux'

components:
  cpu:
    load:
      - detection: snmpget
        oid: ".1.3.6.1.4.1.2021.10.1.3.2"
        operators:
          - type: modify
            modify_method: multiply
            value:
              detection: constant
              value: 100
  memory:
    usage:
      - detection: snmpget
        oid: ".1.3.6.1.4.1.2021.4.6.0"
        operators:
          - type: modify
            modify_method: divide
            value:
              detection: snmpget
              oid: ".1.3.6.1.4.1.2021.4.5.0"
              operators:
                - type: modify
                  modify_method: divide
                  value:
                    detection: constant
                    value: 100
  disk:
    properties:
      detection: snmpwalk
      values:
        type:
          oid: ".1.3.6.1.2.1.25.2.3.1.2"
          operators:
            - type: modify
              modify_method: map
              mappings: hrStorageType.yaml
        description:
          oid: ".1.3.6.1.2.1.25.2.3.1.3"
        available:
          oid: ".1.3.6.1.2.1.25.2.3.1.5"
        used:
          oid: ".1.3.6.1.2.1.25.2.3.1.6"
  server:
    procs:
      - detection: snmpget
        oid: ".1.3.6.1.2.1.25.1.6.0"
    users:
      - detection: snmpget
        oid: "1.3.6.1.2.1.25.1.5.0"