name: "routeros"

match:
  logical_operator: "OR"
  conditions:
    - type: SysObjectID
      match_mode: startsWith
      values:
        - .1.3.6.1.4.1.14988.
    - type: HttpGetBody
      uri: "/"
      match_mode: contains
      values:
        - "RouterOS"

identify:
  properties:
    vendor:
      - detection: constant
        value: "Mikrotik"
    serial_number:
      - detection: snmpget
        oid: "1.3.6.1.4.1.14988.1.1.7.3.0"
    model:
      - detection: SysDescription
        operators:
          - type: modify
            modify_method: regexSubmatch
            regex: '^RouterOS (.+)$'
            format: "$1"
    os_version:
      - detection: snmpget
        oid: "1.3.6.1.4.1.14988.1.1.4.4.0"

components:
  interfaces:
    properties:
      detection: snmpwalk
      values:
        max_speed_in:
          oid: 1.3.6.1.4.1.14988.1.1.1.3.1.3
          operators:
            - type: filter
              filter_method: "!equals"
              value: "0"
        max_speed_out:
          oid: .1.3.6.1.4.1.14988.1.1.1.3.1.2
          operators:
            - type: filter
              filter_method: "!equals"
              value: "0"