name: timos

match:
  conditions:
    - match_mode: startsWith
      type: SysObjectID
      values:
        - ".1.3.6.1.4.1.6527"
  logical_operator: OR

identify:
  properties:
    serial_number:
      - detection: snmpget
        oid: ".1.3.6.1.4.1.6527.3.1.2.2.1.8.1.5.1.50331649"
    vendor:
      - detection: constant
        value: "Nokia"
    os_version:
      - detection: snmpget
        oid: ".1.3.6.1.4.1.6527.3.1.2.2.1.8.1.21.1.134217729"
        operators:
          - type: modify
            modify_method: regexSubmatch
            regex: '^TiMOS-([^, ]+)'
            format: "$1"
    model:
      - detection: snmpget
        oid: ".1.3.6.1.4.1.6527.3.1.2.2.1.8.1.21.1.134217729"
        operators:
          - type: modify
            modify_method: regexSubmatch
            regex: '^(([^, ]+) ){3}([\D,\d]+) Copyright'
            format: "$3"