name: adva_fsp3kr7

match:
  conditions:
    - match_mode: startsWith
      type: SysObjectID
      values:
        - .1.3.6.1.4.1.2544.1.11.1.1
  logical_operator: OR

identify:
  properties:
    vendor:
      - detection: constant
        value: "Adva"
    serial_number:
      - detection: snmpget
        oid: .1.3.6.1.4.1.2544.1.11.2.2.1.17.0
    model:
      - detection: SysDescription
        operators:
          - type: modify
            modify_method: insertReadValue
            read_value:
              detection: snmpget
              oid: .1.3.6.1.4.1.2544.1.11.7.10.1.1.7.1.33.0.0.6
            format: "$property$ ($read_value$)"
    os_version:
      - detection: snmpget
        oid: .1.3.6.1.4.1.2544.1.11.2.2.1.5.0

components:
  interfaces:
    types:
      dwdm:
        detection: 1.3.6.1.4.1.2544.1.11.2.4.3.5.1.3
        specific_values:
          rx_level:
            oid: 1.3.6.1.4.1.2544.1.11.2.4.3.5.1.3
            operators:
              - type: modify
                modify_method: multiply
                value: 0.1
          tx_level:
            oid: 1.3.6.1.4.1.2544.1.11.2.4.3.5.1.4
            operators:
              - type: modify
                modify_method: multiply
                value: 0.1