name: clavister

config:
  components:
    cpu: true
    memory: true

match:
  logical_operator: "OR"
  conditions:
    - type: SysObjectID
      match_mode: startsWith
      values:
        - ".1.3.6.1.4.1.5089.1"

identify:
  properties:
    vendor:
      - detection: constant
        value: "Clavister AB"
    model:
      - detection: SysDescription
        operators:
          - type: modify
            modify_method: regexSubmatch
            regex: '^Clavister ([\D]+)'
            format: "$1"
    os_version:
      - detection: SysDescription
        operators:
          - type: modify
            modify_method: regexSubmatch
            regex: 'Core ([-\d\.]+)'
            format: "$1"

components:
  properties:
    detection: snmpwalk
    values:
      load:
        oid: .1.3.6.1.4.1.5089.1.2.1.1
  memory:
    usage:
      - detection: snmpget
        oid: .1.3.6.1.4.1.5089.1.2.1.12.0
