name: "extremeos"

match:
  logical_operator: "OR"
  conditions:
    - type: SysObjectID
      match_mode: startsWith
      values:
        - .1.3.6.1.4.1.1916.2.291

identify:
  properties:
    vendor:
      - detection: constant
        value: "Extreme Networks"
    os_version:
      - detection: SysDescription
        operators:
          - type: modify
            modify_method: regexSubmatch
            regex: 'ExtremeXOS \(EXOS-VM\) version ([^\s]+)'
            format: "$1"