name: patton-sn

match:
  conditions:
    - match_mode: startsWith
      type: SysObjectID
      values:
        - .1.3.6.1.4.1.1768.100
  logical_operator: OR

identify:
  properties:
    vendor:
      - detection: constant
        value: "Patton"
    model:
      - detection: snmpget
        oid: .1.3.6.1.4.1.1768.100.1.6.0
    serial_number:
      - detection: snmpget
        oid: .1.3.6.1.4.1.1768.100.1.1.0
    os_version:
      - detection: snmpget
        oid: .1.3.6.1.4.1.1768.100.1.5.0
