name: "pfsense"

match:
  logical_operator: "OR"
  conditions:
    - type: SysObjectID
      match_mode: startsWith
      values:
        - .1.3.6.1.4.1.12325

identify:
  properties:
    vendor:
      - detection: constant
        value: "Pfsense"
    os_version:
      - detection: snmpget
        oid: "1.3.6.1.2.1.25.6.3.1.2.1"
        operators:
          - type: modify
            modify_method: regexSubmatch
            regex: 'FreeBSD: FreeBSD ([^\s]+)'
            format: "$1"
    model:
      - detection: SysDescription
        operators:
          - type: modify
            modify_method: regexSubmatch
            regex: '([^\s]+) pfSense.localdomain ([^\s]+)'
            format: "$1 $2"