name: "planetos"

match:
  logical_operator: "OR"
  conditions:
    - type: SysObjectID
      match_mode: startsWith
      values:
        - .1.3.6.1.4.1.10456.

identify:
  properties:
    vendor:
      - detection: constant
        value: "Planet"
    model:
      - detection: SysDescription
        operators:
          - type: modify
            modify_method: regexSubmatch
            regex: 'PLANET ([^\s]+)\s'
            format: "$1"

components:
  interfaces:
    properties:
      detection: snmpwalk
      values:
        ifDescr:
          oid: 1.3.6.1.2.1.2.2.1.2
          operators:
            - type: modify
              modify_method: regexReplace
              regex: '\s+'
              replace: ' '