name: "ES3510MA"

config:
  components:
    cpu: true

match:
  logical_operator: "OR"
  conditions:
    - type: SysObjectID
      match_mode: startsWith
      values:
        - .1.3.6.1.4.1.259.8.1.11.

components:
  cpu:
    load:
      - detection: snmpget
        oid: .1.3.6.1.4.1.259.8.1.11.1.39.2.3.0