name: ubiquiti

match:
  conditions:
    - match_mode: startsWith
      type: SysObjectID
      values:
        - .1.3.6.1.4.1.41112.
  logical_operator: OR

config:
  components:
    cpu: true

identify:
  properties:
    vendor:
      - detection: constant
        value: "Ubiquiti"

components:
  cpu:
    properties:
      detection: snmpwalk
      values:
        load:
          oid: .1.3.6.1.4.1.10002.1.1.1.4.2.1.3.2