name: Lint

on:
  push:
    branches:
      - '*'

jobs:
  fmt:
    name: fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: check
        uses: grandcolline/golang-github-actions@v1.1.0
        with:
          run: fmt
          token: ${{ secrets.GITHUB_TOKEN }}